/**
 * Generated by scripts/prep-drawings.py - do not edit.
 *
 * Each file name carries a hash of its contents, so re-cutting a drawing
 * produces a new URL and no browser can go on showing the previous one. The
 * dimensions travel with the path for the same reason: they cannot drift.
 */
export const drawings = {
  "art-book-hands": {
    "src": "/images/art-book-hands.6747a133.png",
    "width": 900,
    "height": 796
  },
  "art-boy-ball": {
    "src": "/images/art-boy-ball.c9f55f35.png",
    "width": 704,
    "height": 900
  },
  "art-boy-ball-light": {
    "src": "/images/art-boy-ball-light.68407f67.png",
    "width": 704,
    "height": 900
  },
  "art-child-sprawl": {
    "src": "/images/art-child-sprawl.6105b00b.png",
    "width": 786,
    "height": 540
  },
  "art-family-hold": {
    "src": "/images/art-family-hold.c30733a3.png",
    "width": 900,
    "height": 760
  },
  "art-girl-blocks": {
    "src": "/images/art-girl-blocks.0fb6202f.png",
    "width": 698,
    "height": 815
  },
  "art-girl-blocks-light": {
    "src": "/images/art-girl-blocks-light.4ecfb795.png",
    "width": 698,
    "height": 815
  },
  "art-hands-home": {
    "src": "/images/art-hands-home.e42e144d.png",
    "width": 874,
    "height": 900
  },
  "art-mother-walk": {
    "src": "/images/art-mother-walk.60c80bd9.png",
    "width": 752,
    "height": 900
  },
  "art-path-home": {
    "src": "/images/art-path-home.8282bc3e.png",
    "width": 761,
    "height": 833
  },
  "art-tin-can": {
    "src": "/images/art-tin-can.73fbf7c9.png",
    "width": 530,
    "height": 753
  },
  "art-two-women": {
    "src": "/images/art-two-women.28306744.png",
    "width": 900,
    "height": 844
  },
  "art-writing-night": {
    "src": "/images/art-writing-night.0f395902.png",
    "width": 900,
    "height": 815
  },
  "day-collapse": {
    "src": "/images/day-collapse.a1f04afa.png",
    "width": 441,
    "height": 464
  },
  "day-help": {
    "src": "/images/day-help.af63b7a9.png",
    "width": 507,
    "height": 492
  },
  "day-morning": {
    "src": "/images/day-morning.a113819c.png",
    "width": 641,
    "height": 522
  },
  "day-translate": {
    "src": "/images/day-translate.0bca1d05.png",
    "width": 533,
    "height": 397
  }
} as const;
